# Content Areas {-}

Source: <a href="https://www.ascp.org/boc/explore-credentials/view-all-credentials/QLS" target="_blank">ASCP BOC's</a> Qualification in Laboratory Safety, QLS(ASCP)

Major content areas covered:

## **Management** {-}

*   [Administrative](administrative.html)
*   [Regulatory Agencies, Regulations, and Guidelines](regulatory-agencies-regulations-guidelines.html)

## **General Safety** {-}

*   [Ergonomics](/ergonomics-1.html)
*   [Fire Safety](fire-safety.html)
*   [Electrical Safety](electrical-safety.html)
*   [Compressed Gases](compressed-gas.html)
*   [Radiation](radiation.html)
*   [Standard Work Practices](standard-work-practices.html)
*   [Spills and Exposures](spills-exposures.html)

## **Chemical Safety** {-}

*   [Chemical Classifications](chemical-classifications.html)
*   [Incompatible Mixtures](incompatible-mixtures.html)
*   [Signs and Labels](signs-labels-overview.html)
*   [Management](management-2.html)

## **Biohazard Control** {-}

*   [Infection Control](infection-control.html)
*   [Protocols](protocols.html)

## **Physical Environment** {-}

*   [Equipment](equipment.html)
*   [Disinfection and Decontamination](disinfection-decontamination.html)
*   [Disposal and Waste Management](disposal-waste-management.html)